### ISSUE TITLE
企业知识库（BlueVector）

### ISSUE THREAD

**Issue by Ziggy-XX** [maxim-top/maxim-bistro#9]
能否提供企业知识库（BlueVector）示例训练文本?目前有企业使用的需求

**Comment by ericliang** [comment]
你好，如果企业已经有问答库，可以使用这个QA模板 https://github.com/maxim-top/lanying-connector/blob/da26b92be211d0d7a45ef2431d856d83e226787b/bluevector/question-answer.xlsx 

没有也没关系，网站或网页、PDF或者Word等文档也都是可以的，不需要额外处理。
